# -*- coding: utf-8 -*-
"""untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/Friska513/de2d4bf2b0a623ab12aa5b083e6b955d/untitled5.ipynb
"""

import pandas as pd

dataset = pd.read_csv('dataset.csv')

